### ISSUE TITLE
Undefined variable $In in Scanner.php

### ISSUE THREAD

**Issue by tobiasps** [phpMussel/Core#3]
### phpMussel version used (if known, please also include the exact commit hash).
v3.2 from composer

### Signatures version (if known).
Manual installed using SigTool

### PHP SAPI used
cgi-fcgi

### PHP version installed 
7.3.27

### Operating system used
macOS 11.3.1

---
## Issue
I'm seeing the following error in the phpMussel error_log:
```
[2021-05-28T13:23:19+02:00] Error at /Users/.../app/vendor/phpmussel/core/src/Scanner.php:L648 (error code 8): "Undefined variable: In".
```

As far as I can see the variable `$In` should have been `$in` in line 648:
https://github.com/phpMussel/Core/blob/c6e4328f7ab7fd6a7047b751a3749e2e92b9779b/src/Scanner.php#L648

It is also present in the current master:
https://github.com/phpMussel/Core/blob/389dec2d6c055c8ad75822e7ccc3e2baa7c1dae6/src/Scanner.php#L640

### Expected behavior
No error, get length of read data

### Actual behavior
Undefined variable error, no length.

### Steps to reproduce the behavior
* Initialize Scanner from Core, with error_log configured
* Scan file (I tested txt, jpg, and mov files)

**Comment by Maikuolan** [comment]
Good catch, and thanks for reporting this. :-)

I'll start working on a fix now.

**Comment by Maikuolan** [comment]
Fixed. :-)

(You are correct, `$In` should've been `$in`. But, for the fix, I've opted to just change it all to `$In` instead, since it seems like it requires changing less lines than the other way around. Anyway, the problem should be fixed now. I'll push out a new tag/release shortly).
