### ISSUE TITLE
also add MSIX to blacklist

### ISSUE THREAD

**Issue by DanielRuf** [phpMussel/Core#7]
We do not know if some regression will happen and the MSIX protocol handler is enabled again (which happened once, see https://www.theregister.com/2024/01/04/microsoft_windows_app_installation/#:~:text=Microsoft%20re%2Denabled%20the%20protocol,the%20Local%20Group%20Policy%20Editor.).

https://duckduckgo.com/?q=msix+executable+malware&ia=web

**Comment by Maikuolan** [comment]
Good idea. :+1: I'll do that now.

**Comment by Maikuolan** [comment]
Done. :-)
